name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.14', '1.13', '1.12', '1.11' ]
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go }}

    - name: install golint
      run: go get golang.org/x/lint/golint

    - name: run codecov.sh
      run: bash script/codecov.sh

    - name: go vet
      run: go vet $(go list ./... | grep -v /examples/)

    - name: run golint
      run: golint --set_exit_status ./...

    - name: Publish to codecov.io
      run: bash <(curl -s https://codecov.io/bash)
